name: Angular CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and Angular CLI
        run: |
          npm install
          npm install -g @angular/cli

      - name: Run Angular lint
        run: ng lint

      - name: Run Angular tests
        run: ng test
